package io.github.grebeshok105.codex.tag;

import io.github.grebeshok105.codex.ModId;
import net.minecraft.core.registries.Registries;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.EntityType;

/** Mod-owned entity-type tag keys (values generated by {@code ModEntityTypeTagProvider}). */
public final class ModEntityTypeTags {
	/** Entity types Regulus's little-king heart scan can never claim as bearers. */
	public static final TagKey<EntityType<?>> HEARTLESS = TagKey.create(Registries.ENTITY_TYPE, ModId.of("heartless"));

	private ModEntityTypeTags() {
	}
}
